name: Build and Deploy Angular App to Azure Web App - cahinly

on:
  push:
    branches:
      - CICD-Branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Angular production
        run: npm run build -- --configuration production

      - name: Upload Angular build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EDB66B41F36342F9BA3765E0B4DA9772 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_46395FC9C0C141A3A3473710049FDA45 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_097F4B1D4CCA4AA89F9BFAFB910A065A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cahinly'
          slot-name: 'Production'
          package: ./dist/chainly
